/**
 * @file glitch-engine.d.ts
 * @brief Type definitions for the Emscripten-generated WebAssembly module.
 * @description Defines the interface for the C++ GlitchEngine and the Wasm module factory.
 */

/**
 * @interface GlitchEngine
 * @brief Interface representing the C++ class exposed via Emscripten.
 */
export interface GlitchEngine {
    /**
     * @brief Allocates memory buffers in the Wasm heap for the image.
     * @param width The width of the image in pixels.
     * @param height The height of the image in pixels.
     */
    loadBox(width: number, height: number): void;

    /**
     * @brief Returns the memory address (pointer) of the original image buffer.
     * @returns {number} Memory pointer.
     */
    getOriginalPointer(): number;

    /**
     * @brief Returns the memory address (pointer) of the display/render buffer.
     * @returns {number} Memory pointer.
     */
    getDisplayPointer(): number;

    /**
     * @brief Executes the glitch rendering logic for a specific frame.
     * @param x Mouse X coordinate relative to the canvas.
     * @param y Mouse Y coordinate relative to the canvas.
     * @param radius The radius of the effect bubble.
     * @param effectId The integer ID of the effect to apply.
     * @param intensity The intensity parameter for the effect.
     */
    renderFrame(x: number, y: number, radius: number, effectId: number, intensity: number): void;

    /**
     * @brief Destructor to free C++ memory.
     * Automatically generated by Emscripten.
     */
    delete(): void;
}

/**
 * @interface WasmModule
 * @brief Represents the instantiated WebAssembly module.
 */
export interface WasmModule {
    /**
     * @brief Constructor for the GlitchEngine class.
     */
    GlitchEngine: new () => GlitchEngine;

    /**
     * @brief Direct access to the Wasm unsigned 8-bit integer memory heap.
     */
    HEAPU8: Uint8Array;

    /**
     * @brief Optional reference to the WebAssembly memory object (for polyfilling).
     */
    wasmMemory?: WebAssembly.Memory;

    /**
     * @brief Optional reference to the ArrayBuffer (for polyfilling).
     */
    buffer?: ArrayBuffer;
}

/**
 * @typedef GlitchModuleConfig
 * @brief Configuration object for module initialization.
 */
export type GlitchModuleConfig = {
    /**
     * @brief Custom locator for external files (like the .wasm binary).
     * @param path The path to the file to load.
     * @returns The resolved URL or path.
     */
    locateFile?: (path: string) => string;
};

/**
 * @typedef GlitchModuleFactory
 * @brief Function signature for the factory that creates the Wasm module.
 */
export type GlitchModuleFactory = (config?: GlitchModuleConfig) => Promise<WasmModule>;