/**
 * @module glitch_engine
 * @description Module declaration for the specific JS file generated by Emscripten.
 * This overrides the default wildcard declaration to provide strict typing.
 */
declare module '*/glitch_engine.js' {
    const factory: import('./glitch-engine').GlitchModuleFactory;
    export default factory;
}
